
drop table account;

create table account (
  id number generated by default as identity,
  account_id number not null,
  account_ext_id varchar(128) not null,
  is_deleted number(1) default 0 not null,
  b1 float(2) not null,
  b2 float(2) not null,
  b3 float(2) not null,
  primary key(account_id)
);
COMMIT;

BEGIN
 FOR loop_counter IN 1..500
  LOOP
    INSERT INTO account (account_id, account_ext_id, is_deleted, b1, b2, b3)
    VALUES (
      10000 + loop_counter,
      concat('A', to_char(loop_counter * 100)),
      0,
      round(dbms_random.value(0, 400), 2),
      round(dbms_random.value(0, 200), 2),
      round(dbms_random.value(0, 100), 2)
    );
  END LOOP;
  COMMIT;
END;

update account set is_deleted = 1, b1 = 0, b2 = 0, b3 = 0 where mod(id, 10) = 0;