-- select sys_context( 'userenv', 'current_schema' ) from dual;
-- SHOW con_name; show the current database
-- alter session set container = pdborcl;
-- drop table client;
create table client(
  id number generated by default as identity,
  client_id number not null,
  client_ext_id varchar(128) not null,
  primary key(client_id)
);
COMMIT;

BEGIN
 FOR loop_counter IN 1..100
  LOOP
    INSERT INTO client (client_id, client_ext_id)
    VALUES (20000 + loop_counter, concat('C', to_char(loop_counter * 100)));
  END LOOP;
  COMMIT;
END;