drop table relationship_client_account;

create table relationship_client_account (
  id number generated by default as identity,
  client_id number not null,
  account_id number not null,
  primary key (id),
  foreign key (client_id) references client (client_id),
  foreign key (account_id) references account (account_id),
  unique(account_id)
);

COMMIT;

declare 
    cl_index number;
    account_index number;
    max_client_id number;
    min_client_id number;
begin
select max(client_id) into max_client_id from client;
select min(client_id) into min_client_id from client;
for i in 1..150
loop
    select client_id into cl_index from client where client_id = floor(dbms_random.value(min_client_id, max_client_id + 1));
    select account_id into account_index from account where account_id=10000 + i;
    insert into relationship_client_account (client_id, account_id) values (cl_index, account_index);
end loop;
COMMIT;
  end;